# See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates for more information about this file.

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"    
    # Assignees can't be a team unfortunately
    reviewers:
      - "mention-me/partnerships"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Assignees can't be a team unfortunately
    reviewers:
      - "mention-me/partnerships"
